dist: xenial
sudo: required
language: csharp
dotnet: 2.1.500
mono: none
before_script:
- dotnet publish -c Release hello-netcore-mvc.csproj -o hello-netcore-mvc-publish
script:
- dotnet hello-netcore-mvc-publish/hello-netcore-mvc.dll& && curl -v http://127.0.0.1:5000 | grep -i 'Hello .Net Core MVC!'
